name: Build Robot Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Fix line endings and grant execute permissions for gradlew
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      - name: Build with GradleRIO
        run: ./gradlew build